//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RAMEntities : DbContext
    {
        public RAMEntities()
            : base("name=RAMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SubCategoryResult> Proc_Get_SubCategory(string lang, string token)
        {
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubCategoryResult>("Proc_Get_SubCategory", langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<SubCategoryResult> Proc_Get_SubCategory_by_SId(Nullable<int> sID, string lang, string token)
        {
            var sIDParameter = sID.HasValue ?
                new ObjectParameter("SID", sID) :
                new ObjectParameter("SID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubCategoryResult>("Proc_Get_SubCategory_by_SId", sIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<SubCategoryResult> Proc_Get_SubCategory_byTopCategory(Nullable<int> tID, string lang, string token)
        {
            var tIDParameter = tID.HasValue ?
                new ObjectParameter("TID", tID) :
                new ObjectParameter("TID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubCategoryResult>("Proc_Get_SubCategory_byTopCategory", tIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<TopCategoryList> Proc_Get_TopCategory(string lang, string token)
        {
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TopCategoryList>("Proc_Get_TopCategory", langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<TopCategoryList> Proc_TopCategory_by_ID(Nullable<int> tID, string lANG, string token)
        {
            var tIDParameter = tID.HasValue ?
                new ObjectParameter("TID", tID) :
                new ObjectParameter("TID", typeof(int));
    
            var lANGParameter = lANG != null ?
                new ObjectParameter("LANG", lANG) :
                new ObjectParameter("LANG", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TopCategoryList>("Proc_TopCategory_by_ID", tIDParameter, lANGParameter, tokenParameter);
        }
    
        public virtual ObjectResult<CityList> AllCitiesList(string token)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CityList>("AllCitiesList", tokenParameter);
        }
    
        public virtual ObjectResult<CityList> GetCityByProvince(Nullable<int> pid, string token)
        {
            var pidParameter = pid.HasValue ?
                new ObjectParameter("pid", pid) :
                new ObjectParameter("pid", typeof(int));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CityList>("GetCityByProvince", pidParameter, tokenParameter);
        }
    
        public virtual ObjectResult<CityResult> Get_City_By_CId(Nullable<int> cid, string token)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CityResult>("Get_City_By_CId", cidParameter, tokenParameter);
        }
    
        public virtual ObjectResult<ProvinceList> getProvinceByID(string lang, Nullable<int> pid, string token)
        {
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var pidParameter = pid.HasValue ?
                new ObjectParameter("pid", pid) :
                new ObjectParameter("pid", typeof(int));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProvinceList>("getProvinceByID", langParameter, pidParameter, tokenParameter);
        }
    
        public virtual ObjectResult<ProvinceList> getProvinceList(string lang, string token)
        {
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProvinceList>("getProvinceList", langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_Resource_by_Cluster_Search_Keywords(string searchWordS, string lang, string token)
        {
            var searchWordSParameter = searchWordS != null ?
                new ObjectParameter("SearchWordS", searchWordS) :
                new ObjectParameter("SearchWordS", typeof(string));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_Resource_by_Cluster_Search_Keywords", searchWordSParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_All_RamResource_by_Lang(string lang, string token)
        {
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_All_RamResource_by_Lang", langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_All_RamResource(string lang, string token)
        {
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_All_RamResource", langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_Resource_by_City(Nullable<int> cityID, string lang, string token)
        {
            var cityIDParameter = cityID.HasValue ?
                new ObjectParameter("CityID", cityID) :
                new ObjectParameter("CityID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_Resource_by_City", cityIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_Resource_by_ID(Nullable<int> id, string lang, string token)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_Resource_by_ID", idParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_Resource_by_Province(Nullable<int> provinceID, string lang, string token)
        {
            var provinceIDParameter = provinceID.HasValue ?
                new ObjectParameter("ProvinceID", provinceID) :
                new ObjectParameter("ProvinceID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_Resource_by_Province", provinceIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_Resource_by_Province_and_City(Nullable<int> cityID, Nullable<int> provinceID, string lang)
        {
            var cityIDParameter = cityID.HasValue ?
                new ObjectParameter("CityID", cityID) :
                new ObjectParameter("CityID", typeof(int));
    
            var provinceIDParameter = provinceID.HasValue ?
                new ObjectParameter("ProvinceID", provinceID) :
                new ObjectParameter("ProvinceID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_Resource_by_Province_and_City", cityIDParameter, provinceIDParameter, langParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_Resource_by_SubCategory(Nullable<int> subCategoryID, string lang, string token)
        {
            var subCategoryIDParameter = subCategoryID.HasValue ?
                new ObjectParameter("SubCategoryID", subCategoryID) :
                new ObjectParameter("SubCategoryID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_Resource_by_SubCategory", subCategoryIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_Resource_by_Top_and_SubCategory(Nullable<int> tOPCategoryID, Nullable<int> subCategoryID, string lang)
        {
            var tOPCategoryIDParameter = tOPCategoryID.HasValue ?
                new ObjectParameter("TOPCategoryID", tOPCategoryID) :
                new ObjectParameter("TOPCategoryID", typeof(int));
    
            var subCategoryIDParameter = subCategoryID.HasValue ?
                new ObjectParameter("SubCategoryID", subCategoryID) :
                new ObjectParameter("SubCategoryID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_Resource_by_Top_and_SubCategory", tOPCategoryIDParameter, subCategoryIDParameter, langParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_Resource_by_TopCategory(Nullable<int> tOPCategoryID, string lang, string token)
        {
            var tOPCategoryIDParameter = tOPCategoryID.HasValue ?
                new ObjectParameter("TOPCategoryID", tOPCategoryID) :
                new ObjectParameter("TOPCategoryID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_Resource_by_TopCategory", tOPCategoryIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<SuggestionWords> Proc_Get_SuggestionWord_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SuggestionWords>("Proc_Get_SuggestionWord_List");
        }
    
        public virtual ObjectResult<SuggestionWords> Proc_Increment_Suggestion_Word(string l)
        {
            var lParameter = l != null ?
                new ObjectParameter("L", l) :
                new ObjectParameter("L", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SuggestionWords>("Proc_Increment_Suggestion_Word", lParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_All_Resource_In_Radius_boundary_Box(Nullable<decimal> lat, Nullable<decimal> @long, Nullable<decimal> radius, string lang, string token)
        {
            var latParameter = lat.HasValue ?
                new ObjectParameter("Lat", lat) :
                new ObjectParameter("Lat", typeof(decimal));
    
            var longParameter = @long.HasValue ?
                new ObjectParameter("Long", @long) :
                new ObjectParameter("Long", typeof(decimal));
    
            var radiusParameter = radius.HasValue ?
                new ObjectParameter("Radius", radius) :
                new ObjectParameter("Radius", typeof(decimal));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_All_Resource_In_Radius_boundary_Box", latParameter, longParameter, radiusParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_All_Resources_In_Radius(Nullable<decimal> startLatitude, Nullable<decimal> startLongitude, Nullable<decimal> radius, string lang, string token)
        {
            var startLatitudeParameter = startLatitude.HasValue ?
                new ObjectParameter("StartLatitude", startLatitude) :
                new ObjectParameter("StartLatitude", typeof(decimal));
    
            var startLongitudeParameter = startLongitude.HasValue ?
                new ObjectParameter("StartLongitude", startLongitude) :
                new ObjectParameter("StartLongitude", typeof(decimal));
    
            var radiusParameter = radius.HasValue ?
                new ObjectParameter("Radius", radius) :
                new ObjectParameter("Radius", typeof(decimal));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_All_Resources_In_Radius", startLatitudeParameter, startLongitudeParameter, radiusParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<Search_Result> Proc_Cluster_Search_Short(string searchWordS, string lang, string token)
        {
            var searchWordSParameter = searchWordS != null ?
                new ObjectParameter("SearchWordS", searchWordS) :
                new ObjectParameter("SearchWordS", typeof(string));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Result>("Proc_Cluster_Search_Short", searchWordSParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<Search_Result> Proc_Search_Resources_In_Radius(Nullable<decimal> startLatitude, Nullable<decimal> startLongitude, Nullable<decimal> radius, string lang, string token)
        {
            var startLatitudeParameter = startLatitude.HasValue ?
                new ObjectParameter("StartLatitude", startLatitude) :
                new ObjectParameter("StartLatitude", typeof(decimal));
    
            var startLongitudeParameter = startLongitude.HasValue ?
                new ObjectParameter("StartLongitude", startLongitude) :
                new ObjectParameter("StartLongitude", typeof(decimal));
    
            var radiusParameter = radius.HasValue ?
                new ObjectParameter("Radius", radius) :
                new ObjectParameter("Radius", typeof(decimal));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Result>("Proc_Search_Resources_In_Radius", startLatitudeParameter, startLongitudeParameter, radiusParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<Search_Result> Proc_Search_Resource_In_Radius_boundary_Box(Nullable<decimal> lat, Nullable<decimal> @long, Nullable<decimal> radius, string lang, string token)
        {
            var latParameter = lat.HasValue ?
                new ObjectParameter("Lat", lat) :
                new ObjectParameter("Lat", typeof(decimal));
    
            var longParameter = @long.HasValue ?
                new ObjectParameter("Long", @long) :
                new ObjectParameter("Long", typeof(decimal));
    
            var radiusParameter = radius.HasValue ?
                new ObjectParameter("Radius", radius) :
                new ObjectParameter("Radius", typeof(decimal));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Result>("Proc_Search_Resource_In_Radius_boundary_Box", latParameter, longParameter, radiusParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<Search_Result> Proc_Search_Resource_by_City(Nullable<int> cityID, string lang, string token)
        {
            var cityIDParameter = cityID.HasValue ?
                new ObjectParameter("CityID", cityID) :
                new ObjectParameter("CityID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Result>("Proc_Search_Resource_by_City", cityIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<Search_Result> Proc_Search_Resource_by_Province(Nullable<int> provinceID, string lang, string token)
        {
            var provinceIDParameter = provinceID.HasValue ?
                new ObjectParameter("ProvinceID", provinceID) :
                new ObjectParameter("ProvinceID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Result>("Proc_Search_Resource_by_Province", provinceIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<Search_Result> Proc_Search_Resource_by_SubCategory(Nullable<int> subCategoryID, string lang, string token)
        {
            var subCategoryIDParameter = subCategoryID.HasValue ?
                new ObjectParameter("SubCategoryID", subCategoryID) :
                new ObjectParameter("SubCategoryID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Result>("Proc_Search_Resource_by_SubCategory", subCategoryIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<Search_Result> Proc_Search_Resource_by_TopCategory(Nullable<int> tOPCategoryID, string lang, string token)
        {
            var tOPCategoryIDParameter = tOPCategoryID.HasValue ?
                new ObjectParameter("TOPCategoryID", tOPCategoryID) :
                new ObjectParameter("TOPCategoryID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Result>("Proc_Search_Resource_by_TopCategory", tOPCategoryIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_Unique_Resource(string map, string resourceAgencyNum, Nullable<int> subcategoryid, Nullable<int> topcategoryid, string lang, string token)
        {
            var mapParameter = map != null ?
                new ObjectParameter("map", map) :
                new ObjectParameter("map", typeof(string));
    
            var resourceAgencyNumParameter = resourceAgencyNum != null ?
                new ObjectParameter("resourceAgencyNum", resourceAgencyNum) :
                new ObjectParameter("resourceAgencyNum", typeof(string));
    
            var subcategoryidParameter = subcategoryid.HasValue ?
                new ObjectParameter("subcategoryid", subcategoryid) :
                new ObjectParameter("subcategoryid", typeof(int));
    
            var topcategoryidParameter = topcategoryid.HasValue ?
                new ObjectParameter("topcategoryid", topcategoryid) :
                new ObjectParameter("topcategoryid", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_Unique_Resource", mapParameter, resourceAgencyNumParameter, subcategoryidParameter, topcategoryidParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_Resource_By_Coverage(string s, string lang, string token)
        {
            var sParameter = s != null ?
                new ObjectParameter("s", s) :
                new ObjectParameter("s", typeof(string));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_Resource_By_Coverage", sParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<Search_Result> Proc_Search_Resource_By_Coverage(string s, string lang, string token)
        {
            var sParameter = s != null ?
                new ObjectParameter("s", s) :
                new ObjectParameter("s", typeof(string));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Result>("Proc_Search_Resource_By_Coverage", sParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<string> Proc_Get_Allow_Domain()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Proc_Get_Allow_Domain");
        }
    
        public virtual ObjectResult<string> Proc_Get_Allow_IP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Proc_Get_Allow_IP");
        }
    }
}
